name: shape_up
description: Fitness tracking app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  intl_translation: ^0.21.0

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Database & Backend
  supabase_flutter: ^2.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.9.0
  
  # Image picker
  image_picker: ^1.0.5
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Utils
  csv: ^5.1.1
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  
  # Charts
  fl_chart: ^0.66.0

  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/foods.csv
    - .env